[
  ./kitty.nix
  ./rofi.nix
  ./polybar.nix
  ./cava.nix
  ./dunst.nix
  ./music.nix
  ./obs-studio/obs_studio.nix
  ./search.nix
  ./mpv/mpv.nix
  ./imgview.nix
  ./hugo.nix
  ./neofetch/neofetch.nix
  ./ranger/ranger.nix
  ./fcitx5/fcitx5-theme.nix
  ./libinput-gestures.nix
]
